import { regexToNFA } from "./thompson.js";
// subset.js
// Block 1: ε-closure
// ─────────────────────────────────────────────────────────────
// epsilonClosure(transitions, stateIdSet) → Set of state id strings
//
// transitions : the full nfa.transitions array from AutomataObject
// stateIdSet  : a JS Set of state id strings (e.g. new Set(['q0']))

function epsilonClosure(transitions, stateIdSet) {
  const closure = new Set(stateIdSet);
  const stack = [...stateIdSet];
  while (stack.length > 0) {
    const state = stack.pop();
    for (const t of transitions) {
      if (t.from === state && t.symbol === "ε") {
        if (!closure.has(t.to)) {
          closure.add(t.to);
          stack.push(t.to);
        }
      }
    }
  }
  return closure;
}

// ─── Block 2: move ────────────────────────────────────────────
// Theory: move(T, a) = all NFA states reachable from any state
//         in T by consuming exactly one input symbol 'a'.
//         No ε-transitions are followed here.
//
// @param transitions  - nfa.transitions array  [{from, to, symbol}]
// @param stateIdSet   - a Set of NFA state id strings (a DFA "state")
// @param symbol       - a single input character e.g. 'a' or 'b'
// @returns            - a new Set of NFA state id strings
function move(transitions, stateIdSet, symbol) {
  const result = new Set();

  for (const t of transitions) {
    if (stateIdSet.has(t.from) && t.symbol === symbol) {
      result.add(t.to);
    }
  }
  return result;
}

// ─── Block 3: nfaToDFA skeleton ───────────────────────────────
// Theory: DFA states are subsets of NFA states.
//         Initial DFA state = ε-closure({ nfa_start }).
//         BFS explores all reachable subsets systematically.

export function nfaToDFA(nfa) {
  // A: Canonical string key for a Set of NFA state IDs
  const setKey = (s) => [...s].sort().join(",");

  // B: Derive real alphabet from transitions (fixes hardcoded bug)
  const alphabet = [
    ...new Set(nfa.transitions.map((t) => t.symbol).filter((s) => s !== "ε")),
  ];

  // C: Compute the initial DFA state
  const nfaStart = nfa.states.find((s) => s.isStart).id;
  const startClosure = epsilonClosure(nfa.transitions, new Set([nfaStart]));
  const startKey = setKey(startClosure);

  // D: BFS data structures
  const queue = [startClosure];
  const visited = new Set([startKey]);
  const dfaStatesMap = new Map();
  const dfaTransitions = [];

  dfaStatesMap.set(startKey, startClosure);

  // ─── Block 4: BFS loop ────────────────────────────────────────
  // Theory: Process each DFA state (NFA subset) by computing
  //         ε-closure(move(T, a)) for every symbol a in alphabet.

  while (queue.length > 0) {
    const currentSet = queue.shift();
    const currentKey = setKey(currentSet);
    for (const symbol of alphabet) {
      const moved = move(nfa.transitions, currentSet, symbol);
      const nextSet = epsilonClosure(nfa.transitions, moved);
      const nextKey = setKey(nextSet);
      dfaTransitions.push({ from: currentKey, to: nextKey, symbol });
      if (!visited.has(nextKey)) {
        visited.add(nextKey);
        dfaStatesMap.set(nextKey, nextSet);
        queue.push(nextSet);
      }
    }
  }
  // ─── Block 5: Output assembly ─────────────────────────────────
  // Theory: A DFA state is accepting iff it contains
  //         at least one NFA accepting state.

  // A: Collect NFA accept state IDs for fast lookup
  const nfaAcceptIds = new Set(
    nfa.states.filter((s) => s.isAccept).map((s) => s.id),
  );

  // B: Build DFA states array
  const dfaStates = [];

  for (const [key, nfaSubset] of dfaStatesMap) {
    const isStart = key === startKey;
    const isAccept = [...nfaSubset].some((id) => nfaAcceptIds.has(id));
    const label = key === "" ? "∅" : key;

    dfaStates.push({
      id: key,
      label: label,
      isStart: isStart,
      isAccept: isAccept,
      position: { x: 0, y: 0 },
    });
  }

  // C: DFA transitions (already correct shape from Block 4)
  const dfaTransitionObjects = dfaTransitions.map((t) => ({
    from: t.from,
    to: t.to,
    symbol: t.symbol,
  }));

  // D: Return complete AutomataObject
  return {
    type: "DFA",
    alphabet: alphabet,
    states: dfaStates,
    transitions: dfaTransitionObjects,
    meta: {
      sourceRE: nfa.meta?.sourceRE ?? "",
      description: "Generated by subset construction from NFA",
    },
  };
}
// testString — simulates a DFA on an input string
// Returns true if the DFA accepts the string, false if it rejects
export function testString(dfa, input) {
  let current = dfa.states.find((s) => s.isStart).id;

  for (const ch of input) {
    const t = dfa.transitions.find(
      (t) => t.from === current && t.symbol === ch,
    );
    if (!t) return false; // no transition = reject
    current = t.to;
  }

  return dfa.states.find((s) => s.id === current)?.isAccept ?? false;
}
