function epsilonClosure(transitions, stateIdSet) {
  const closure = new Set(stateIdSet);
  const stack = [...stateIdSet];
  while (stack.length > 0) {
    const state = stack.pop();
    for (const t of transitions) {
      if (t.from === state && t.symbol === "ε") {
        if (!closure.has(t.to)) {
          closure.add(t.to);
          stack.push(t.to);
        }
      }
    }
  }
  return closure;
}

function move(transitions, stateIdSet, symbol) {
  const result = new Set();
  for (const t of transitions) {
    if (stateIdSet.has(t.from) && t.symbol === symbol) {
      result.add(t.to);
    }
  }
  return result;
}

export function nfaToDFA(nfa) {
  const setKey = (s) => [...s].sort().join(",");

  const alphabet = [
    ...new Set(
      nfa.transitions.map((t) => t.symbol).filter((s) => s && s !== "ε"),
    ),
  ];

  const nfaStart = nfa.states.find((s) => s.isStart).id;
  const startClosure = epsilonClosure(nfa.transitions, new Set([nfaStart]));
  const startKey = setKey(startClosure);

  const queue = [startClosure];
  const visited = new Set([startKey]);
  const dfaStatesMap = new Map();
  const rawTransitions = [];

  dfaStatesMap.set(startKey, startClosure);

  while (queue.length > 0) {
    const currentSet = queue.shift();
    const currentKey = setKey(currentSet);

    for (const symbol of alphabet) {
      const moved = move(nfa.transitions, currentSet, symbol);
      const nextSet = epsilonClosure(nfa.transitions, moved);
      const nextKey = setKey(nextSet);

      rawTransitions.push({ from: currentKey, to: nextKey, symbol });

      if (!visited.has(nextKey)) {
        visited.add(nextKey);
        dfaStatesMap.set(nextKey, nextSet);
        queue.push(nextSet);
      }
    }
  }

  const stateKeys = Array.from(dfaStatesMap.keys());
  const idMapping = {};
  stateKeys.forEach((key, index) => {
    idMapping[key] = key === "" ? "∅" : `S${index}`;
  });

  const nfaAcceptIds = new Set(
    nfa.states.filter((s) => s.isAccept).map((s) => s.id),
  );

  const dfaStates = [];
  for (const [key, nfaSubset] of dfaStatesMap) {
    dfaStates.push({
      id: idMapping[key],
      label: idMapping[key],
      isStart: key === startKey,
      isAccept: [...nfaSubset].some((id) => nfaAcceptIds.has(id)),
      position: { x: 0, y: 0 },
    });
  }

  const dfaTransitions = rawTransitions.map((t) => ({
    from: idMapping[t.from],
    to: idMapping[t.to],
    symbol: t.symbol,
  }));

  return {
    type: "DFA",
    alphabet: alphabet,
    states: dfaStates,
    transitions: dfaTransitions,
    meta: {
      sourceRE: nfa.meta?.sourceRE ?? "",
      description: "Generated by subset construction from NFA",
    },
  };
}

export function testString(dfa, input) {
  const startNode = dfa.states.find((s) => s.isStart);
  if (!startNode) return false;
  let current = startNode.id;
  for (const ch of input) {
    const t = dfa.transitions.find(
      (t) => t.from === current && t.symbol === ch,
    );
    if (!t) return false;
    current = t.to;
  }
  const finalNode = dfa.states.find((s) => s.id === current);
  return finalNode ? finalNode.isAccept : false;
}
