function epsilonClosure(transitions, stateIdSet) {
  const closure = new Set(stateIdSet);
  const stack = [...stateIdSet];
  while (stack.length > 0) {
    const state = stack.pop();
    for (const t of transitions) {
      if (t.from === state && (t.symbol === "ε" || t.label === "ε")) {
        if (!closure.has(t.to)) {
          closure.add(t.to);
          stack.push(t.to);
        }
      }
    }
  }
  return closure;
}

function move(transitions, stateIdSet, char) {
  const result = new Set();
  for (const t of transitions) {
    const transitionChar = t.symbol || t.label;
    if (stateIdSet.has(t.from) && transitionChar === char) {
      result.add(t.to);
    }
  }
  return result;
}

export function nfaToDFA(nfa) {
  const setKey = (s) => [...s].sort().join(",");
  const alphabet = [
    ...new Set(
      nfa.transitions
        .map((t) => t.symbol || t.label)
        .filter((s) => s && s !== "ε"),
    ),
  ];

  const nfaStart = nfa.states.find((s) => s.isStart).id;
  const startClosure = epsilonClosure(nfa.transitions, new Set([nfaStart]));
  const startKey = setKey(startClosure);

  const queue = [startClosure];
  const visited = new Set([startKey]);
  const dfaStatesMap = new Map();
  const rawTransitions = [];

  dfaStatesMap.set(startKey, startClosure);

  while (queue.length > 0) {
    const currentSet = queue.shift();
    const currentKey = setKey(currentSet);

    for (const char of alphabet) {
      const moved = move(nfa.transitions, currentSet, char);
      const nextSet = epsilonClosure(nfa.transitions, moved);

      if (nextSet.size > 0) {
        const nextKey = setKey(nextSet);

        rawTransitions.push({ from: currentKey, to: nextKey, label: char });

        if (!visited.has(nextKey)) {
          visited.add(nextKey);
          dfaStatesMap.set(nextKey, nextSet);
          queue.push(nextSet);
        }
      }
    }
  }

  const stateKeys = Array.from(dfaStatesMap.keys());
  const idMapping = {};
  stateKeys.forEach((key, index) => {
    idMapping[key] = `S${index}`;
  });

  const nfaAcceptIds = new Set(
    nfa.states.filter((s) => s.isAccept).map((s) => s.id),
  );

  const dfaStates = [];
  for (const [key, nfaSubset] of dfaStatesMap) {
    const isStart = key === startKey;
    const isAccept = [...nfaSubset].some((id) => nfaAcceptIds.has(id));

    dfaStates.push({
      id: idMapping[key],
      label: idMapping[key],
      isStart: isStart,
      isAccept: isAccept,
      position: { x: 0, y: 0 },
    });
  }

  const dfaTransitions = rawTransitions.map((t) => ({
    from: idMapping[t.from],
    to: idMapping[t.to],
    label: t.label,
  }));

  return {
    type: "DFA",
    alphabet: alphabet,
    states: dfaStates,
    transitions: dfaTransitions,
    meta: {
      sourceRE: nfa.meta?.sourceRE ?? "",
      description: "Generated by subset construction",
    },
  };
}

export function testString(dfa, input) {
  const startNode = dfa.states.find((s) => s.isStart);
  if (!startNode) return false;

  let current = startNode.id;

  for (const ch of input) {
    const t = dfa.transitions.find((t) => t.from === current && t.label === ch);
    if (!t) return false;
    current = t.to;
  }

  const finalNode = dfa.states.find((s) => s.id === current);
  return finalNode ? finalNode.isAccept : false;
}
